# Generated by Django 2.1.4 on 2018-12-23 16:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('database_name', models.CharField(max_length=200)),
                ('process_name', models.CharField(max_length=200)),
                ('lastcomplete_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('status', models.CharField(max_length=10)),
                ('issuspended', models.CharField(max_length=10)),
                ('interval', models.IntegerField()),
                ('average', models.IntegerField()),
                ('laginseconds', models.IntegerField()),
            ],
        ),
    ]
